config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  get '/auth/:provider/callback', to: 'sessions#create'

  resources :projects do
    resources :reviews
    resources :sheets

    member do
      get :view3d
    end
  end
end

app/models/credential.rb
class Credential < ActiveRecord::Base
  # https://www.twilio.com/blog/2014/09/gmail-api-oauth-rails.html
  require 'net/http'
  require 'json'

  def to_params
    {
      'refresh_token' => refresh_token,
      'client_id' => Rails.application.secrets.client_id,
      'client_secret' => Rails.application.secrets.client_secret,
      'grant_type' => 'refresh_token'
    }
  end

  def request_token
    url = URI("https://accounts.google.com/o/oauth2/token")
    Net::HTTP.post_form(url, to_params)
  end

  def refresh!
    response = request_token
    data = JSON.parse(response.body)
    update_attributes(
      token: data['access_token'],
      expires_at: Time.now + (data['expires_in'].to_i).seconds)
  end

  def expired?
    expires_at < Time.now
  end

  def fresh_token
    refresh! if expired?
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :sheets, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # Move to serializer
  def as_json(*args)
    {
      "versions": [ # The first version needs to be the most recent
        {
          "id": 1,
          # "urn": "urn:dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Zm9yZ2UtamF2YS1zYW1wbGUtYXBwLTdpdGw0a2dobmticGZhNjdzcTZxbGRla3d0dHJtYmR2L215LXNhbXBsdC5ydnQ"
          # "urn": "urn:dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Zm9yZ2UtamF2YS1zYW1wbGUtYXBwLTdpdGw0a2dobmticGZhNjdzcTZxbGRla3d0dHJtYmR2L3Jldml0Mi5ydnQ"

          # "urn": "urn:dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Zm9yZ2UtamF2YS1zYW1wbGUtYXBwLTdpdGw0a2dobmticGZhNjdzcTZxbGRla3d0dHJtYmR2L3Jldml0NC5ydnQ"
          
          "urn": "urn:dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Zm9yZ2UtamF2YS1zYW1wbGUtYXBwLTdpdGw0a2dobmticGZhNjdzcTZxbGRla3d0dHJtYmR2L3Jldml0Ni5ydnQ"
        },
        {
          "id": 2,
          # "urn": "urn:dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Zm9yZ2UtamF2YS1zYW1wbGUtYXBwLTdpdGw0a2dobmticGZhNjdzcTZxbGRla3d0dHJtYmR2L215LXNhbXBsZS1vbGQucnZ0"
          # "urn": "urn:dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Zm9yZ2UtamF2YS1zYW1wbGUtYXBwLTdpdGw0a2dobmticGZhNjdzcTZxbGRla3d0dHJtYmR2L3Jldml0LnJ2dA"

          # "urn": "urn:dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Zm9yZ2UtamF2YS1zYW1wbGUtYXBwLTdpdGw0a2dobmticGZhNjdzcTZxbGRla3d0dHJtYmR2L3Jldml0My5ydnQ"

          "urn": "urn:dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Zm9yZ2UtamF2YS1zYW1wbGUtYXBwLTdpdGw0a2dobmticGZhNjdzcTZxbGRla3d0dHJtYmR2L3Jldml0NS5ydnQ"
        }
      ]
    }
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :project

  after_create :process_version


  def process_version
    # google_drive_version_id
    # send bytes to autodesk and get urn
  end

  # def create_bucket(bucket_key,access_token)
  #   response = RestClient.post("#{API_URL}/oss/v2/buckets",
  #                              { bucketKey: bucket_key, policyKey:'persistent'}.to_json,
  #                              { Authorization: "Bearer #{access_token}", content_type:'application/json' })
  #   return response

end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  belongs_to :project

  enum :status, :not_reviewed, :approved, :not_approved
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @credential ||= Credential.find_by(id: session[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_project, only: [:show, :view3d]

  def create
    @project = Project.create(project_params)
    render 'uploading'
  end

  def view3d
    render layout: false
  end

  private

  def load_project
    @project = Project.find(params[:id])
    @auth_token = AutodeskToken.get
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_project
  before_action :load_review, only: [:show]

  def show
    @auth_token = AutodeskToken.get
  end

  def create
    @review = @project.reviews.create
    redirect_to [@project, @review]
  end

  private

  def load_project
    @project = Project.find(params[:project_id])
  end

  def load_review
    @review = Review.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @credential = Credential.find_or_create_by(email: auth_hash['info']['email'])

    @credential.update(
      token:         auth_hash['credentials']['token'],
      refresh_token: auth_hash['credentials']['refresh_token'],
      expires_at:    Time.at(auth_hash['credentials']['expires_at']).to_datetime
    )

    session[:id] = @credential.id
    request.env['omniauth.origin']
    redirect_to request.env['omniauth.origin'] || root_path
  end

  def destroy
    session[:id] = nil
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    qualified_controller_name = controller.controller_path.gsub('/','-')
    "#{qualified_controller_name} #{qualified_controller_name}-#{controller.action_name}"
  end
end

app/helpers/oauth_helper.rb
require 'google/apis/drive_v3'
require 'googleauth'
require 'googleauth/stores/file_token_store'


module OauthHelper
  OOB_URI = 'urn:ietf:wg:oauth:2.0:oob'
  APPLICATION_NAME = 'Drive API Ruby Quickstart'
  # CLIENT_SECRETS_PATH = 'client_secret.json'
  # CREDENTIALS_PATH = File.join(Dir.home, '.credentials',
  #                              "drive-ruby-quickstart.yaml")
  SCOPE = Google::Apis::DriveV3::AUTH_DRIVE

  # authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
  # json_key_io: File.open('/path/to/service_account_json_key.json'),
  # scope: scope)

  # authorizer.fetch_access_token!

  # Ensure valid credentials, either by restoring from the saved credentials
  # files or intitiating an OAuth2 authorization. If authorization is required,
  # the user's default browser will be launched to approve the request.
  #
  # @return [Google::Auth::UserRefreshCredentials] OAuth2 credentials
  def authorize
    # FileUtils.mkdir_p(File.dirname(CREDENTIALS_PATH))

    p client_id = Rails.application.secrets.client_id
    # token_store = Google::Auth::Stores::FileTokenStore.new(file: CREDENTIALS_PATH)
    authorizer = Google::Auth::UserAuthorizer.new(client_id, SCOPE, token_store)

    user_id = 'default'
    credentials = authorizer.get_credentials(user_id)
    if credentials.nil?
      url = authorizer.get_authorization_url(
        base_url: OOB_URI)
      puts "Open the following URL in the browser and enter the " +
           "resulting code after authorization"
      puts url
      code = gets
      credentials = authorizer.get_and_store_credentials_from_code(
        user_id: user_id, code: code, base_url: OOB_URI)
    end
    credentials

    # Initialize the API
    service = Google::Apis::DriveV3::DriveService.new
    service.client_options.application_name = APPLICATION_NAME
    service.authorization = authorize
    response = service.list_files(page_size: 10,
                                  fields: 'nextPageToken, files(id, name)')

    puts "\nStart token"
    start_token = service.get_changes_start_page_token
    puts start_token.inspect

    puts "\nDrive change list"
    changes = service.list_changes(145205)
    puts changes.inspect

    # puts "\nRevision list"
    # revisions = service.list_revisions('1hOC1ShRXHxyFz8hVnbPzypr3pr_lRWEL')
    # puts revisions.inspect

    # puts "\nGet one file"
    # file = service.get_file('1hOC1ShRXHxyFz8hVnbPzypr3pr_lRWEL', download_dest: "/home/rtrifan/Coding/hackathons/builtworlds/file")
    # puts file.inspect

    # puts "\nGet one revision"
    # response = service.get_revision('1hOC1ShRXHxyFz8hVnbPzypr3pr_lRWEL', '0B7HMrQcKw_OMekxuOXRsQlM3aGpJV1hPSldBUEs5RDhkbk9VPQ', download_dest: "/home/rtrifan/Coding/hackathons/builtworlds/revision_last")
    # puts response
    end
  end

app/views/layouts/application.html.slim
html
  head
  title Otter Challenge
  = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:300,400,700"
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag "https://developer.api.autodesk.com/modelderivative/v2/viewers/three.min.js?v=v3.2.*"
  = javascript_include_tag "https://developer.api.autodesk.com/modelderivative/v2/viewers/viewer3D.min.js?v=v3.2.*"
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  body class=body_class

    nav.navbar.navbar-expand-lg.navbar-light.bg-light
      a.navbar-brand href=root_path Review

      .collapse.navbar-collapse
        ul.navbar-nav.mr-auto
          - if @project
            li.nav-item.active
              = link_to @project.name, @project, class: "nav-link"

    = yield

app/views/projects/index.html.slim
.container
  .card.mt-4.w-50{style = "height:400px"}
    .card-header
      h3.card-title Projects
    .card-body
      p.card-text To start your review, start by selecting a tendering project
      p
        form
          .row
            .col
              input.form-control.mr-sm-2[type="search" placeholder="Project Name" aria-label="Search"]
            .col-auto
              button.btn.btn-outline-success.my-2.my-sm-0[type="submit"] Search
        - if Project.any?
          hr
        - Project.limit(10).each do |review|
          p
            = link_to review.name, review, data: { turbolinks: false }
      p
        a.card-link[href="#"] 1370 Harrison West Road, SF
      p
        a.card-link[href="#"]  965 W Chicago Ave, Chicago
      p
        = link_to "Create", new_project_path, class: 'btn btn-primary'


javascript:

app/views/projects/new.html.slim
.container
  .card.mt-4{style = "height:400px"}
    h3.card-header Files
    .card-body
      .text-center.google-button
        - if current_user
          = link_to "/signout", class: "btn btn-primary google-button" do
            i.fa.fa-google.fa-lg>
            |  Sign out from Google Drive
        - else
          = link_to "/auth/google_oauth2", class: "btn btn-primary google-button" do
            i.fa.fa-google.fa-lg>
            | Login to Google Drive to pick files
      .loading.text-center.collapse
        i.fa.fa-spinner.fa-2x.fa-spin.text-muted
      .files.collapse
        h4 Select a file
        .mt-4= link_to "Small House Model", projects_path(project: { name: "Small House Model" }), method: :post
        .mt-4= link_to "Fancy House Model", projects_path(project: { name: "Fancy House Model" }), method: :post
        .mt-4= link_to "Forest House Model", projects_path(project: { name: "Forest House Model" }), method: :post


javascript:
  $(".google-button").click(function(e) {
    e.preventDefault();
    $(".google-button").fadeOut("fast", function() {
      $(".loading").fadeIn("fast");
      setTimeout(function() {
        $(".loading").hide();
        $(".files").fadeIn();
      }, 2000);
    });
  });


  javascript:
//     // The Browser API key obtained from the Google API Console.
//     // Replace with your own Browser API key, or your own key.
//     var developerKey = 'AIzaSyCad2qxnCI2WFEzMoZC6h5ksnAqwTuO5Po';

//     // The Client ID obtained from the Google API Console. Replace with your own Client ID.
//     var clientId = "1076103330137-fq88m5jm1ib4t022b6q84o182r92ekcd.apps.googleusercontent.com";

//     // Replace with your own project number from console.developers.google.com.
//     // See "Project number" under "IAM & Admin" > "Settings"
//     var appId = "1076103330137";

//     // Scope to use to access user's Drive items.
//     var scope = ['https://www.googleapis.com/auth/drive'];

//     var pickerApiLoaded = false;
//     var oauthToken = "#{current_user.token}";

//     // Use the Google API Loader script to load the google.picker script.
//     function loadPicker() {
//       // gapi.load('auth', {'callback': onAuthApiLoad});
//       gapi.load('picker', {'callback': onPickerApiLoad});
//     }

//     function onAuthApiLoad() {
//       window.gapi.auth.authorize(
//           {
//             'client_id': clientId,
//             'scope': scope,
//             'immediate': false
//           },
//           handleAuthResult);
//     }

//     function onPickerApiLoad() {
//       pickerApiLoaded = true;
//       createPicker();
//     }

//     function handleAuthResult(authResult) {
//       if (authResult && !authResult.error) {
//         oauthToken = authResult.access_token;
//         createPicker();
//       }
//     }

//     // Create and render a Picker object for searching images.
//     function createPicker() {
//       if (pickerApiLoaded && oauthToken) {
//         var view = new google.picker.View(google.picker.ViewId.DOCS);
//         view.setMimeTypes("image/png,image/jpeg,image/jpg");
//         var picker = new google.picker.PickerBuilder()
//             .enableFeature(google.picker.Feature.NAV_HIDDEN)
//             .enableFeature(google.picker.Feature.MULTISELECT_ENABLED)
//             .setAppId(appId)
//             .setOAuthToken(oauthToken)
//             .addView(view)
//             .addView(new google.picker.DocsUploadView())
//             .setDeveloperKey(developerKey)
//             .setCallback(pickerCallback)
//             .build();
//          picker.setVisible(true);
//       }
//     }

//     // A simple callback implementation.
//     function pickerCallback(data) {
//       if (data.action == google.picker.Action.PICKED) {
//         var fileId = data.docs[0].id;
//         alert('The user selected: ' + fileId);
//       }
//     }

// script type="text/javascript" src="https://apis.google.com/js/api.js?onload=loadPicker"

app/views/projects/show.html.slim
.container-fluid.mt-4
  .row
    .col
      .card
        .card-body
          .row
            .col
              h5 Model Sheets
            .col-auto
              = link_to project_reviews_path(@project), method: :post do
                i.fa.fa-plus.fa-lg>
                | Start a new review
          table.table
            thead.thead-light
              tr
                th Name
                th Last Reviewed
                th # of Changes
                th Status
            tr
              td Cover Sheets
              td= 20.day.ago.to_formatted_s(:short)
              td= 451
              td.text-center
                i.fa.fa-circle.text-danger
            tr
              td Floor Plans
              td= 20.day.ago.to_formatted_s(:short)
              td.text-muted= 0
              td.text-center
                i.fa.fa-circle.text-success
            tr
              td Partition Plans
              td= 10.day.ago.to_formatted_s(:short)
              td 15
              td.text-center
                i.fa.fa-circle.text-warning


    .col
      - if @project.reviews.any?
        .card
          .card-body
            h5 Review History
            table.table
              thead.thead-light
                tr
                  th Name
                  th Date
                  th Since
                  th Author
              - @project.reviews.each do |review|
                  tr
                    td Review
                    td= review.created_at
                    td= time_ago_in_words(review.created_at)
                    td= Faker::Name.name

      .card class=("mt-4" if @project.reviews.any?)
        .card-body
          h5 3D View - Architectural Model
          iframe src=view3d_project_path(@project) style="height: 350px; width: 100%; background-color: gray; border: 0;"

app/views/projects/uploading.html.slim
.container
  h4.mt-4 Uploading to Forge
  p This may take a minute

  .progress
    .progress-bar.progress-bar-striped.progress-bar-animated style="transition: width 1s;" data={ path: project_path(@project) }

javascript:
  var progress = 0;
  setInterval(function() {
    progress = progress + Math.floor(Math.random() * (25 - 15)) + 15;
    progress = Math.min(progress, 100);
    $(".progress-bar").css("width", progress.toString() + "%");

    if(progress == 100) {
      setTimeout(function() {
        window.location = $(".progress-bar").data("path");
      }, 500);
    }
  }, 1000)

app/views/projects/view3d.html.slim
html
  head
    = javascript_include_tag "https://developer.api.autodesk.com/modelderivative/v2/viewers/three.min.js?v=v3.2.*"
    = javascript_include_tag "https://developer.api.autodesk.com/modelderivative/v2/viewers/viewer3D.min.js?v=v3.2.*"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag "https://developer.api.autodesk.com/modelderivative/v2/viewers/style.min.css"

  body style="overflow: hidden;"
    #viewer style="height: 350px; background-color: gray;"

    javascript:
      window.loadView(#{raw @project.as_json[:versions].last[:urn].to_json}, #{raw @auth_token.to_json}, "viewer")

app/views/reviews/show.html.slim
= stylesheet_link_tag "https://developer.api.autodesk.com/modelderivative/v2/viewers/style.min.css"

.container-fluid
  .row.editor
    .col
      #Viewer3dDiv
    .col
      #Viewer2dDiv
    .col-auto style="padding: 0 0 0 15px;"
      #SheetPane

  .text-right.mt-4
    = link_to "Reject", @project, class: "btn btn-danger mr-4"
    = link_to "Approve", @project, class: "btn btn-success"

javascript:
  loadProject(#{raw @project.to_json}, #{raw @auth_token.to_json})

app/views/welcome/index.html.slim
= stylesheet_link_tag "https://developer.api.autodesk.com/modelderivative/v2/viewers/style.min.css"
= javascript_include_tag "https://developer.api.autodesk.com/modelderivative/v2/viewers/three.min.js?v=v3.2.*"
= javascript_include_tag "https://developer.api.autodesk.com/modelderivative/v2/viewers/viewer3D.min.js?v=v3.2.*"
= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"

css:
  body {
      margin: 0;
  }
  #Viewer2dDiv,
  #Viewer3dDiv {
      width: 100%;
      height: 100%;
      margin: 0;
      background-color: #F0F8FF;
  }
  #Viewer2dDiv {
      margin-left: 50%;
  }
  .adsk-viewing-viewer {
      width: 50% !important;
  }

javascript:
  var accessToken = "eyJhbGciOiJIUzI1NiIsImtpZCI6Imp3dF9zeW1tZXRyaWNfa2V5In0.eyJjbGllbnRfaWQiOiI3SVRMNEtnSG5LQlBGQTY3U3E2UWxkRUtXdFRSbUJEViIsImV4cCI6MTUxMjI0NDU4OCwic2NvcGUiOlsiZGF0YTpyZWFkIiwiZGF0YTp3cml0ZSIsImJ1Y2tldDpjcmVhdGUiXSwiYXVkIjoiaHR0cHM6Ly9hdXRvZGVzay5jb20vYXVkL2p3dGV4cDYwIiwianRpIjoid2NzRGRvTG5wdmNhWXZuSGN1TEtJb09mNlZEOTV4V3o1RXJ0YkgxeTBURHg3R3Y1cExuZnhXTlNodkdnRUNMcyJ9.goAbX8YB-ITr1XNFAtBkHFVvD-1xJGAnMnQiT8XFzQ8"
  var viewer2d;
  var viewer3d;
  var options = {
      env: 'AutodeskProduction',
      accessToken: accessToken
  };
  var documentId = 'urn:dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Zm9yZ2UtamF2YS1zYW1wbGUtYXBwLTdpdGw0a2dobmticGZhNjdzcTZxbGRla3d0dHJtYmR2L215LXNhbXBsdC5ydnQ';
  Autodesk.Viewing.Initializer(options, function onInitialized(){
      Autodesk.Viewing.Document.load(documentId, onDocumentLoadSuccess, onDocumentLoadFailure);
  });

  /**
  * Autodesk.Viewing.Document.load() success callback.
  * Proceeds with model initialization.
  */
  function onDocumentLoadSuccess(doc) {

      // A document contains references to 3D and 2D viewables.
      var viewables2d = Autodesk.Viewing.Document.getSubItemsWithProperties(doc.getRootItem(), {'type':'geometry'}, true);
      var viewables3d = Autodesk.Viewing.Document.getSubItemsWithProperties(doc.getRootItem(), {'type':'geometry', 'role': '3d'}, true);
      if (viewables2d.length === 0 || viewables3d === 0) {
          console.error('Document contains no viewables.');
          return;
      }

      // Choose any of the avialble viewables
      var initialViewable2d = viewables2d[0];
      var initialViewable3d = viewables3d[0];
      var svfUrl2d = doc.getViewablePath(initialViewable2d);
      var svfUrl3d = doc.getViewablePath(initialViewable3d);
      var modelOptions = {
          sharedPropertyDbPath: doc.getPropertyDbPath()
      };

      var viewerDiv2d = document.getElementById('Viewer2dDiv');
      var viewerDiv3d = document.getElementById('Viewer3dDiv');
      viewer2d = new Autodesk.Viewing.Private.GuiViewer3D(viewerDiv2d);
      viewer2d.start(svfUrl2d, modelOptions, onLoadModelSuccess, onLoadModelError);
      viewer3d = new Autodesk.Viewing.Private.GuiViewer3D(viewerDiv3d);
      viewer3d.start(svfUrl3d, modelOptions, onLoadModelSuccess, onLoadModelError);
  }

  /**
   * Autodesk.Viewing.Document.load() failuire callback.
   */
  function onDocumentLoadFailure(viewerErrorCode) {
      console.error('onDocumentLoadFailure() - errorCode:' + viewerErrorCode);
  }

  /**
   * viewer.loadModel() success callback.
   * Invoked after the model's SVF has been initially loaded.
   * It may trigger before any geometry has been downloaded and displayed on-screen.
   */
  function onLoadModelSuccess(model) {
      console.log('onLoadModelSuccess()!');
      console.log('Validate model loaded: ' + (viewer.model === model));
      console.log(model);
  }

  /**
   * viewer.loadModel() failure callback.
   * Invoked when there's an error fetching the SVF file.
   */
  function onLoadModelError(viewerErrorCode) {
      console.error('onLoadModelError() - errorCode:' + viewerErrorCode);
  }


h1 JKLSDJF

#Viewer2dDiv
#Viewer3dDiv